import { Geist, Geist_Mono ,Assistant} from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/UserContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const assistant = Assistant({
  subsets: ['latin'],
  weight: ['400', '700'], // Match the font weights you're using
  variable: '--font-assistant', // CSS variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${assistant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </UserProvider>
  );
}
